[package]
name = "send"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
askama = "0.12.1"
axum = "0.7.5"
thiserror = "1.0.61"
tokio = "1.38.0"
tower = "0.4.13"
tower-http = "0.5.2"
